In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('C:/Users/Thousand Sunny/Downloads/respiratory_df_cleaned.csv')

In [5]:
df

,Week Start Date,Week End Date,Hospital County,Percent of visits for acute respiratory diseases,Percent of visits for COVID-19,Percent of visits for influenza,Percent of visits for RSV,MMWR Week,Visit type_y,Group,Subgroup,Population,"Rate of acute respiratory visits (per 100,000 residents)","Rate of COVID visit per 100,000","Rate of RSV visits per 100,000","Rate of Influenza visits per 100,000",Number of acute respiratory visits by out of state patients
0,11/5/2023,11/11/2023,Norfolk,0.159319,0.011022,0.004008,0.008016,45,Admissions,Patient county,Plymouth,5.308190e+05,43.517659,3.579375,2.260658,1.507105,0
1,11/5/2023,11/11/2023,Norfolk,0.159319,0.011022,0.004008,0.008016,45,Admissions,Patient county,Middlesex,1.632002e+06,29.718101,2.818624,1.348038,0.306372,0
2,11/5/2023,11/11/2023,Norfolk,0.159319,0.011022,0.004008,0.008016,45,Admissions,Patient county,Out of state,0.000000e+00,0.000000,0.000000,0.000000,0.000000,102
3,11/5/2023,11/11/2023,Norfolk,0.159319,0.011022,0.004008,0.008016,45,Admissions,Patient county,Bristol,5.792000e+05,45.407459,3.453039,2.244475,0.517956,0
4,11/5/2023,11/11/2023,Norfolk,0.159319,0.011022,0.004008,0.008016,45,Admissions,Patient county,Worcester,8.621110e+05,51.849472,5.103751,4.175796,0.231989,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68255,7/2/2023,7/8/2023,Essex,0.082329,0.005227,0.001016,0.000000,27,ED visits,Race,Black or African American,5.758497e+05,111.487418,6.077975,0.000000,1.562908,0
68256,7/2/2023,7/8/2023,Essex,0.082329,0.005227,0.001016,0.000000,27,ED visits,Patient county,Norfolk,7.259810e+05,55.648839,2.066170,0.275489,0.413234,0
68257,7/2/2023,7/8/2023,Essex,0.082329,0.005227,0.001016,0.000000,27,Admissions,Hispanic ethnicity,Not Hispanic or Latino,6.150973e+06,25.004175,1.609501,0.081288,0.146318,0
68258,7/2/2023,7/8/2023,Essex,0.082329,0.005227,0.001016,0.000000,27,Admissions,Hispanic ethnicity,"Unknown ethnicity, not reported, or not catego...",0.000000e+00,0.000000,0.000000,0.000000,0.000000,0
68259,7/2/2023,7/8/2023,Essex,0.082329,0.005227,0.001016,0.000000,27,Admissions,Hispanic ethnicity,Hispanic or Latino,8.789442e+05,24.119848,0.910183,0.000000,0.227546,0

In [6]:
overall_stats = df.describe()

In [7]:
overall_stats

,Percent of visits for acute respiratory diseases,Percent of visits for COVID-19,Percent of visits for influenza,Percent of visits for RSV,MMWR Week,Population,"Rate of acute respiratory visits (per 100,000 residents)","Rate of COVID visit per 100,000","Rate of RSV visits per 100,000","Rate of Influenza visits per 100,000",Number of acute respiratory visits by out of state patients
count,68260.000000,68260.000000,68260.000000,68260.000000,68260.000000,6.826000e+04,68260.000000,68260.000000,68260.000000,68260.000000,68260.000000
mean,0.170486,0.030328,0.012001,0.005425,31.208541,9.783799e+05,83.115271,12.004148,2.911371,5.810950,5.753560
std,0.085954,0.031016,0.038245,0.013433,16.251773,1.421014e+06,107.013883,18.478678,10.487099,15.153558,39.148323
min,0.032258,0.000000,0.000000,0.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.116438,0.014721,0.000000,0.000000,27.000000,7.102900e+04,15.061737,0.487641,0.000000,0.000000,0.000000
50%,0.158664,0.024030,0.001903,0.001266,35.000000,5.758497e+05,45.586304,6.134460,0.246966,0.553798,0.000000
75%,0.203508,0.037705,0.016667,0.006505,44.000000,1.208696e+06,114.412479,15.289656,2.182984,3.807360,0.000000
max,1.000000,0.400000,1.000000,0.200000,52.000000,6.150973e+06,954.051210,224.065199,170.365898,252.542967,637.000000

In [16]:
unique_groups = df['Group'].unique()

# This will print the unique values from the 'Group' column
print(unique_groups)

['Patient county' 'Race' 'Age' 'Hispanic ethnicity' 'Sex']

In [22]:
unique_groups = df['Subgroup'].unique()

# This will print the unique values from the 'Group' column
print(unique_groups)

['Plymouth' 'Middlesex' 'Out of state' 'Bristol' 'Worcester' 'Dukes'
 'Essex' 'Hampshire' 'Suffolk' 'Norfolk' 'Berkshire' 'Barnstable'
 'Franklin' 'Nantucket' 'Hampden' 'White' 'Other Race'
 'Black or African American' '50-64 years' '35-49 years' '80+ years'
 '20-34 years' '65-79 years' 'Under 5 years' '5-19 years' 'Asian'
 'Multiracial' 'Not Hispanic or Latino' 'Male' 'Hispanic or Latino'
 'Native Hawaiian or Other Pacific Islander'
 'American Indian or Alaska Native' 'Female'
 'Unknown race, not reported, or not categorized'
 'Unknown ethnicity, not reported, or not categorized' 'Unknown sex'
 'Unknown age']

In [13]:
demographics_stats = df[['Group', 'Rate of acute respiratory visits (per 100,000 residents)',
                         'Rate of COVID visit per 100,000', 'Rate of RSV visits per 100,000',
                         'Rate of Influenza visits per 100,000', 
                         'Number of acute respiratory visits by out of state patients']].describe()
demographics_stats

,"Rate of acute respiratory visits (per 100,000 residents)","Rate of COVID visit per 100,000","Rate of RSV visits per 100,000","Rate of Influenza visits per 100,000",Number of acute respiratory visits by out of state patients
count,68260.000000,68260.000000,68260.000000,68260.000000,68260.000000
mean,83.115271,12.004148,2.911371,5.810950,5.753560
std,107.013883,18.478678,10.487099,15.153558,39.148323
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,15.061737,0.487641,0.000000,0.000000,0.000000
50%,45.586304,6.134460,0.246966,0.553798,0.000000
75%,114.412479,15.289656,2.182984,3.807360,0.000000
max,954.051210,224.065199,170.365898,252.542967,637.000000

In [20]:
patient_county_stats = df[df['Group'] == 'Patient county'][[
    'Rate of acute respiratory visits (per 100,000 residents)',
    'Rate of COVID visit per 100,000', 
    'Rate of RSV visits per 100,000',
    'Rate of Influenza visits per 100,000', 
    'Number of acute respiratory visits by out of state patients'
]].describe()

# Output the summary statistics for 'Patient county'
print(patient_county_stats)

patient_county_stats

       Rate of acute respiratory visits (per 100,000 residents)  \
count                                       28500.000000
mean                                           90.461967
std                                           105.872960
min                                             0.000000
25%                                            31.495059
50%                                            57.536694
75%                                           121.383650
max                                           954.051210

       Rate of COVID visit per 100,000  Rate of RSV visits per 100,000  \
count                     28500.000000                    28500.000000
mean                         12.952507                        2.538712
std                          14.636117                        5.813255
min                           0.000000                        0.000000
25%                           3.875188                        0.000000
50%                           8.625576                        0.429346
75%                          17.092541                        2.506467
max                          98.211154                       72.815534

       Rate of Influenza visits per 100,000  \
count                          28500.000000
mean                               6.572944
std                               17.823469
min                                0.000000
25%                                0.000000
50%                                0.616113
75%                                4.366889
max                              252.542967

       Number of acute respiratory visits by out of state patients
count                                       28500.000000
mean                                           13.780281
std                                            59.667001
min                                             0.000000
25%                                             0.000000
50%                                             0.000000
75%                                             0.000000
max                                           637.000000

,"Rate of acute respiratory visits (per 100,000 residents)","Rate of COVID visit per 100,000","Rate of RSV visits per 100,000","Rate of Influenza visits per 100,000",Number of acute respiratory visits by out of state patients
count,28500.000000,28500.000000,28500.000000,28500.000000,28500.000000
mean,90.461967,12.952507,2.538712,6.572944,13.780281
std,105.872960,14.636117,5.813255,17.823469,59.667001
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,31.495059,3.875188,0.000000,0.000000,0.000000
50%,57.536694,8.625576,0.429346,0.616113,0.000000
75%,121.383650,17.092541,2.506467,4.366889,0.000000
max,954.051210,98.211154,72.815534,252.542967,637.000000

In [25]:
#for overall age statistics
subgroup_age_stats = df[df['Subgroup'].isin([
    '50-64 years', '35-49 years', '80+ years',
    '20-34 years', '65-79 years', 'Under 5 years', '5-19 years'
])][[
    'Rate of acute respiratory visits (per 100,000 residents)',
    'Rate of COVID visit per 100,000', 
    'Rate of RSV visits per 100,000',
    'Rate of Influenza visits per 100,000', 
    'Number of acute respiratory visits by out of state patients'
]].describe()

# Output the summary statistics for 'Patient county'
print(subgroup_age_stats)

subgroup_age_stats

       Rate of acute respiratory visits (per 100,000 residents)  \
count                                       13300.000000
mean                                          125.551109
std                                           136.475213
min                                             1.902877
25%                                            27.482219
50%                                            79.055715
75%                                           175.456989
max                                           677.498915

       Rate of COVID visit per 100,000  Rate of RSV visits per 100,000  \
count                     13300.000000                    13300.000000
mean                         20.752561                        6.453528
std                          29.708821                       21.205453
min                           0.000000                        0.000000
25%                           2.293666                        0.069225
50%                           8.686419                        0.535189
75%                          26.582297                        2.802071
max                         224.065199                      170.365898

       Rate of Influenza visits per 100,000  \
count                          13300.000000
mean                               7.867033
std                               14.615805
min                                0.000000
25%                                0.382278
50%                                1.401035
75%                                7.005177
max                              108.159929

       Number of acute respiratory visits by out of state patients
count                                            13300.0
mean                                                 0.0
std                                                  0.0
min                                                  0.0
25%                                                  0.0
50%                                                  0.0
75%                                                  0.0
max                                                  0.0

,"Rate of acute respiratory visits (per 100,000 residents)","Rate of COVID visit per 100,000","Rate of RSV visits per 100,000","Rate of Influenza visits per 100,000",Number of acute respiratory visits by out of state patients
count,13300.000000,13300.000000,13300.000000,13300.000000,13300.0
mean,125.551109,20.752561,6.453528,7.867033,0.0
std,136.475213,29.708821,21.205453,14.615805,0.0
min,1.902877,0.000000,0.000000,0.000000,0.0
25%,27.482219,2.293666,0.069225,0.382278,0.0
50%,79.055715,8.686419,0.535189,1.401035,0.0
75%,175.456989,26.582297,2.802071,7.005177,0.0
max,677.498915,224.065199,170.365898,108.159929,0.0

In [27]:
pip install XlsxWriter

Requirement already satisfied: XlsxWriter in c:\users\thousand sunny\anaconda3\lib\site-packages (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [28]:
age_groups = [
    '50-64 years', '35-49 years', '80+ years',
    '20-34 years', '65-79 years', 'Under 5 years', '5-19 years'
]

rate_columns = [
    'Rate of acute respiratory visits (per 100,000 residents)',
    'Rate of COVID visit per 100,000', 
    'Rate of RSV visits per 100,000',
    'Rate of Influenza visits per 100,000', 
    'Number of acute respiratory visits by out of state patients'
]

# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('age_group_stats.xlsx', engine='xlsxwriter')

# Iterate over each age group, filter the DataFrame, calculate statistics, and write to a separate sheet in the Excel file.
for age_group in age_groups:
    filtered_df = df[df['Subgroup'] == age_group][rate_columns]
    stats = filtered_df.describe()
    
    # Write each age group's statistics to a separate sheet
    stats.to_excel(writer, sheet_name=age_group)

# Close the Pandas Excel writer and output the Excel file.
writer.save()

print("Statistics for each age group have been saved to 'age_group_stats.xlsx'.")

Statistics for each age group have been saved to 'age_group_stats.xlsx'.

In [29]:
#reading the file containing covid-19 data fro massachusetts 
ds = pd.read_csv('C:/Users/Thousand Sunny/Downloads/covid_mass_df_cleaned.csv')

In [30]:
ds

,Week Start Date,Week End Date,Group,Subgroup,Estimated population,Percent of the population,Week case rate,Cumulative cases,Cumulative case rate,Deaths during this week,...,County,Population,Cases during this week_y,Cumulative confirmed cases,Cumulative tests,Tests during the week,Positive tests the week,Week percent positivity,Weekly case rate,Weekly testing rate
0,2023-07-02,2023-07-08,Race and Hispanic ethnicity,"Hispanic, all races",878944.174599,0.125029,14.904246,131.0,14.904246,0,...,Barnstable,2.289960e+05,57.0,57.0,1014.0,1014.0,73.0,0.071992,24.891264,442.802495
1,2023-07-02,2023-07-08,Race and Hispanic ethnicity,"Hispanic, all races",878944.174599,0.125029,14.904246,131.0,14.904246,0,...,Berkshire,1.290260e+05,6.0,6.0,508.0,508.0,6.0,0.011811,4.650226,393.719095
2,2023-07-02,2023-07-08,Race and Hispanic ethnicity,"Hispanic, all races",878944.174599,0.125029,14.904246,131.0,14.904246,0,...,Bristol,5.792000e+05,35.0,35.0,597.0,597.0,36.0,0.060302,6.042818,103.073204
3,2023-07-02,2023-07-08,Race and Hispanic ethnicity,"Hispanic, all races",878944.174599,0.125029,14.904246,131.0,14.904246,0,...,Dukes and Nantucket,3.485500e+04,3.0,3.0,104.0,104.0,4.0,0.038462,8.607087,298.378999
4,2023-07-02,2023-07-08,Race and Hispanic ethnicity,"Hispanic, all races",878944.174599,0.125029,14.904246,131.0,14.904246,0,...,Essex,8.098290e+05,65.0,65.0,1380.0,1380.0,70.0,0.050725,8.026386,170.406345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10195,2024-02-18,2024-02-24,Age,Unknown age,0.000000,0.000000,0.000000,6.0,0.000000,0,...,Plymouth,5.308190e+05,79.0,6728.0,61560.0,1420.0,102.0,0.071831,14.882662,267.511148
10196,2024-02-18,2024-02-24,Age,Unknown age,0.000000,0.000000,0.000000,6.0,0.000000,0,...,Statewide (all of MA),7.029917e+06,1469.0,85750.0,928773.0,27017.0,1669.0,0.061776,20.896406,384.314637
10197,2024-02-18,2024-02-24,Age,Unknown age,0.000000,0.000000,0.000000,6.0,0.000000,0,...,Suffolk,7.979360e+05,146.0,8479.0,99137.0,3171.0,167.0,0.052665,18.297207,397.400293
10198,2024-02-18,2024-02-24,Age,Unknown age,0.000000,0.000000,0.000000,6.0,0.000000,0,...,Unknown,0.000000e+00,5.0,400.0,8642.0,251.0,5.0,0.000000,0.000000,0.000000
10199,2024-02-18,2024-02-24,Age,Unknown age,0.000000,0.000000,0.000000,6.0,0.000000,0,...,Worcester,8.621110e+05,188.0,9863.0,110385.0,3624.0,215.0,0.059327,21.806937,420.363502

In [33]:
o_stats = ds.describe()
o_stats

,Estimated population,Percent of the population,Week case rate,Cumulative cases,Cumulative case rate,Week death rate,Cumulative death rate,Confirmed deaths,Confirmed cases,Population,Cases during this week_y,Cumulative confirmed cases,Cumulative tests,Tests during the week,Positive tests the week,Week percent positivity,Weekly case rate,Weekly testing rate
count,1.020000e+04,10200.000000,10200.000000,10200.000000,10200.000000,10200.000000,10200.000000,10200.000000,10200.000000,1.020000e+04,10200.000000,10200.000000,10200.000000,10200.000000,10200.000000,10200.000000,10200.000000,10200.000000
mean,1.038185e+06,0.102681,35.434899,7527.498529,576.595183,0.434147,6.284171,23.882353,2522.058824,9.373223e+05,336.274510,4911.760784,55025.952941,3642.247059,369.384314,0.088906,35.346243,405.101705
std,1.347187e+06,0.152374,43.553499,11178.143537,781.602317,1.434723,23.400378,11.772340,1245.646348,1.681417e+06,691.396074,11506.320246,125172.001044,6840.259098,757.304218,0.039540,22.721164,197.370533
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,607.000000,0.000000e+00,0.000000,2.000000,104.000000,104.000000,0.000000,0.000000,0.000000,0.000000
25%,1.380839e+03,0.000196,0.000000,256.250000,0.000000,0.000000,0.000000,15.000000,1674.000000,1.290260e+05,46.000000,336.000000,5556.000000,661.000000,51.000000,0.066118,20.926015,281.402278
50%,4.935132e+05,0.051122,24.817290,2913.000000,317.648731,0.000000,0.112152,23.500000,2258.000000,5.308190e+05,148.000000,1571.000000,18646.500000,1743.000000,172.500000,0.087949,32.272001,405.529812
75%,1.342105e+06,0.138935,51.965541,10215.500000,850.857547,0.303960,2.940622,31.000000,3067.000000,8.098290e+05,290.000000,4454.000000,50480.000000,3265.000000,324.000000,0.116713,46.824556,524.294435
max,4.826116e+06,0.686511,308.255377,65796.000000,5015.613296,13.258296,200.200266,50.000000,5347.000000,7.029917e+06,5347.000000,85750.000000,928773.000000,40856.000000,5825.000000,0.187919,124.893011,941.041457

In [34]:
unique_groups = ds['Group'].unique()

# This will print the unique values from the 'Group' column
print(unique_groups)

['Race and Hispanic ethnicity' 'Reported sex or gender' 'Age']

In [35]:
unique_groups = ds['Subgroup'].unique()

# This will print the unique values from the 'Group' column
print(unique_groups)

['Hispanic, all races' 'Asian, not Hispanic'
 'Black or African-American, not Hispanic'
 'Alaskan Native or American Indian, not Hispanic'
 'Other race, not Hispanic'
 'Native Hawaiian or Pacific Islander, not Hispanic' 'White, not Hispanic'
 'Unknown race' 'Female' 'Male' 'Transgender' 'Unknown sex' '<5 years'
 '5-19 years' '20-34 years' '35-49 years' '50-64 years' '65-79 years'
 '80+ years' 'Unknown age']

In [42]:
# Define the age groups and rate columns as before

covidage_groups = ['<5 years', '5-19 years', '20-34 years', '35-49 years', '50-64 years', '65-79 years', '80+ years']

covidrate_columns = [
    'Cumulative tests',
    'Cumulative confirmed cases', 
    'Cumulative cases',
    'Week death rate', 
    'Positive tests the week',
]

# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('covidage_group_stats.xlsx', engine='xlsxwriter')

# Iterate over each age group, filter the DataFrame, calculate statistics, and write to a separate sheet in the Excel file.
for covidage_group in covidage_groups:
    # Corrected filtering using the variable 'covidage_group' instead of the list 'covidage_groups'
    filtered_df = ds[ds['Subgroup'] == covidage_group][covidrate_columns]
    stats = filtered_df.describe()
    
    # Write each age group's statistics to a separate sheet
    # Excel sheet names have a character limit, so we ensure the name is not too long
    sheet_name = covidage_group[:31] if len(covidage_group) > 31 else covidage_group
    stats.to_excel(writer, sheet_name=sheet_name)

# Close the Pandas Excel writer and output the Excel file.
writer.save()

print("Statistics for each COVID-19 age group have been saved to 'covidage_group_stats.xlsx'.")

Statistics for each COVID-19 age group have been saved to 'covidage_group_stats.xlsx'.